method: 'DPM-SNC'
exp_name: 'HPO'
seed: 0
# data : pubmed, citeseer, cora, Photo, Computers
data:
  data: Computers
  dir: './data'
  nfeat: 767
  nlabel: 10

# temp: temperatures in constructing a buffer
diffusion:
  method: LP
  # method: Continuous
  step: 80
  s: 0.008
  coef: 1
  temp: 0.3
  simple_temp: 0.25
  priority_temp: 0.01
  multichain: False
  estep_corr_dist: 'Unif' # Unif, UM, LF-Unif, LF-UM (UM - uncertainty minimization, LF - labeled first)
  eval_corr_dist: 'LF-Unif' # Unif, UM, LF-Unif, LF-UM (UM - uncertainty minimization, LF - labeled first)
  weightts: False
  emphasize_labeled: True
  learn_identity: True

model:
  model: GCNConv
  denoise_model: v1
  nhid: 64
  num_layers: 2
  num_linears: 1
  type: 1    # 1 - ourGCN,  0 - pyg GCN

# load_start: number of iterations in initial maximization step
# load_interval: number of iterations in maximization step
train:
  load_start: 2000
  num_epochs: 15000
  pre_train_epochs: 500
  lr_simple: 0.005
  print_interval: 100
  load_interval: 100
  time_batch: 8
  lr: 0.005
  lr_diffusion: 0.005
  weight_decay: 0.001
  weight_decay_diffusion: 0.001
  lr_schedule: False
  grad_norm: 1
  lr_decay: 0.99999
  priority_queue: True


# {'method': 'DPM-SNC', 'exp_name': 'HPO', 'seed': 0,
#  'data': {'data': 'Computers', 'dir': './data', 'nfeat': 767, 'nlabel': 10},
#  'diffusion': {'method': 'LP', 'step': 80, 's': 0.008, 'coef': 1, 'temp': 0.3, 'simple_temp': 0.25, 'priority_temp': 0.01, 'multichain': False, 'estep_corr_dist': 'Unif', 'eval_corr_dist': 'LF-Unif', 'weightts': False, 'emphasize_labeled': True, 'learn_identity': False},
#  'model': {'model': 'GCNConv', 'denoise_model': 'v1', 'nhid': 64, 'num_layers': 2, 'num_linears': 1},
#  'train': {'load_start': 2000, 'num_epochs': 15000, 'pre_train_epochs': 500,
#            'lr_simple': 0.005, 'print_interval': 100, 'load_interval': 100, 'time_batch': 8,
#            'lr': 0.005, 'lr_diffusion': 0.005,
#            'weight_decay': 0.001, 'weight_decay_diffusion': 0.001,
#            'lr_schedule': False, 'grad_norm': 1, 'lr_decay': 0.99999, 'priority_queue': True}}
