method: 'DPM-SNC'
exp_name: 'PHOTO'
seed: 0
# data : pubmed, citeseer, cora, Photo, Computers
data:
  data: Photo
  dir: './data'
  nfeat: 745
  nlabel: 8

# temp: temperatures in constructing a buffer
diffusion:
  method: Continuous
  step: 80
  s: 0.008
  coef: 1
  temp: 0.3
  simple_temp: 0.3
  priority_temp: 0.1
  multichain: False
  estep_corr_dist: 'Unif' # Unif, UM, LF-Unif, LF-UM (UM - uncertainty minimization, LF - labeled first)
  eval_corr_dist: 'LF-Unif' # Unif, UM, LF-Unif, LF-UM (UM - uncertainty minimization, LF - labeled first)
  weightts: False
  emphasize_labeled: True
  learn_identity: True

model:
  model: GATConv
  denoise_model: v1
  nhid: 8
  num_layers: 2
  num_linears: 1

# load_start: number of iterations in initial maximization step
# load_interval: number of iterations in maximization step
train:
  load_start: 2000
  num_epochs: 15000
  pre_train_epochs: 500
  lr_simple: 0.005
  print_interval: 100
  load_interval: 100
  time_batch: 8
  lr: 0.001
  lr_diffusion: 0.001
  weight_decay: 0.005
  weight_decay_diffusion: 0.005
  lr_schedule: False
  grad_norm: 1
  lr_decay: 0.99999
  priority_queue: False
