method: 'DPM-SNC-LP'
exp_name: 'HPO'
seed: 0
# data : pubmed, citeseer, cora, Cornell, Texas, Wisconsin, Photo, Computers
data:
  data: ogbn-products
  dir: './data'
  nfeat: 100
  nlabel: 47

# temp: temperatures in constructing a buffer
diffusion:
  method: LP
  # method: Continuous
  step: 80
  s: 0.008
  coef: 1
  temp: 0.1
  simple_temp: 0.1
  priority_temp: 0.1
  multichain: False
  estep_corr_dist: 'Unif' # Unif, UM, LF-Unif, LF-UM (UM - uncertainty minimization, LF - labeled first)
  eval_corr_dist: 'LF-Unif' # Unif, UM, LF-Unif, LF-UM (UM - uncertainty minimization, LF - labeled first)
  weightts: False
  emphasize_labeled: True
  learn_identity: True

model:
  model: GCNConv
  denoise_model: v1
  nhid: 64
  num_layers: 2
  num_linears: 1

# load_start: number of iterations in initial maximization step
# load_interval: number of iterations in maximization step
train:
  load_start: 2000
  num_epochs: 20000
  pre_train_epochs: 500
  lr_simple: 0.005
  print_interval: 100
  load_interval: 100
  time_batch: 16
  lr: 0.01
  lr_diffusion: 0.01
  weight_decay: 0.01
  weight_decay_diffusion: 0.01
  lr_schedule: False
  grad_norm: 1
  lr_decay: 0.99999
  priority_queue: False
